require("./bootstrap");
global.$ = global.jQuery = require("jquery");
require("jquery-ui");
require("jquery-ui/ui/widgets/mouse");
require("jquery-ui/ui/widgets/draggable");
require("jquery-ui/ui/widgets/droppable");
require("./jquery.nicescroll.min.js");
require("sweetalert2");
require("datatables.net-bs4");
require("fullcalendar");
require("./stisla");
require("./scripts");
require("./custom");
